version: 2.1

orbs:
  node: circleci/node@4.7.0
  windows: circleci/windows@2.4.0
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@2.0.3

commands: 
  set_s3_pkg_urls:
    steps:
      - run:
          name: Set S3 URLs according to date and git hash
          environment:
            GIT_REVISION: << pipeline.git.revision >>
            PIPELINE_NUMBER: << pipeline.number >>
          command: |
            echo "export S3_PKG_BUCKET=salto-rocksdb-prebuilds" >> $BASH_ENV
            echo "export PKG_PREFIX=${GIT_REVISION:0:8}" >> $BASH_ENV
            source $BASH_ENV
            echo "export S3_PKG_HASH_PREFIX=s3://${S3_PKG_BUCKET}/${CIRCLE_BRANCH}/${PKG_PREFIX}" >> $BASH_ENV
            source $BASH_ENV

jobs:
  prebuild_windows:
    executor:
      name: windows/default
      shell: powershell.exe
    # currently the windows build is not passing
    steps:
      - checkout
      - run:
          name: setup node and yarn
          command: |
            nvm on
            nvm install 12.22.1
            nvm use 12.22.1
            nvm alias default 12.22.1
            $NpmPath=[Environment]::GetEnvironmentVariable("ProgramW6432")+"\nodejs"
            $regexAddPath = [regex]::Escape($addPath)
            $arrPath = $env:Path -split ';' | Where-Object {$_ -notMatch "^$regexAddPath\\?"}
            $env:Path = ($arrPath + $NpmPath) -join ';'
            npm install --global yarn@1.22.11
      - run:
          name: install packages
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Prebuild windows binary
          command: |
            yarn prebuild
      - persist_to_workspace:
          root: .
          paths: prebuilds/win32-x64

  prebuild_macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: 12.22.1
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
          with-cache: false
          include-branch-in-cache-key: false
      - run:
          name: Prebuild binary
          command: yarn prebuild --tag-libc
      - persist_to_workspace:
          root: .
          paths: prebuilds/darwin-x64

  prebuild_linux:
    docker:
      - image: cimg/node:12.22.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
          with-cache: false
          include-branch-in-cache-key: false
      - run:
          name: Prebuild binary
          command: yarn prebuild --tag-libc
      - persist_to_workspace:
          root: .
          paths: prebuilds/linux-x64

  upload_to_s3:
    docker:
      - image: cimg/node:12.22.1
    steps:
      - aws-cli/install:
          version: 2.2.2
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
      - set_s3_pkg_urls
      - run:
          name: archive prebuilds
          command: tar cvf prebuilds/ prebuilds.tar
      - aws-s3/sync:
          from: prebuilds.tar
          to: ${S3_PKG_HASH_PREFIX}/prebuilds.tar

workflows:
  prebuild:
    jobs:
      - prebuild_linux:
          filters:
            branches:
              only: master
      - prebuild_macos:
          filters:
            branches:
              only: master
      - prebuild_windows:
          filters:
            branches:
              only: master
      - upload_to_s3:
          requires:
            - prebuild_windows
            - prebuild_macos
            - prebuild_linux
          filters:
            branches:
              only: master
